### ISSUE TITLE
Deployment works but not sure how to run it

### ISSUE THREAD

**Issue by davidebbo** [shibayan/AzureRubyDeployment#1]
I deployed it to a new site. The deployment was successful:

```
Counting objects: 23, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (23/23), 3.95 KiB | 0 bytes/s, done.
Total 23 (delta 8), reused 23 (delta 8)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'f530e2cf7a'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: Installing ruby runtime.
remote: ......................................................................................................................
................
remote: Installing bundler
remote: ........
remote: Handling Ruby Web Site deployment.
remote: KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
remote: Deleting file: 'hostingstart.html'
remote: Copying file: '.gitattributes'
remote: Copying file: 'README.md'
remote: Copying file: 'startup.bat'
remote: Copying file: 'Web.config'
remote: Finished successfully.
remote: Deployment successful.
To https://davidebbo@davidruby.scm.azurewebsites.net:443/DavidRuby.git
 * [new branch]      master -> master
```

But then, I'm not sure what's supposed to happen when I hit the site. It's hanging, and I see an error in `eventlog.xml`:

```
    <Event>
        <System>
            <Provider Name="HttpPlatformHandler"/>
            <EventID>1000</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2014-12-04T18:34:33Z"/>
            <EventRecordID>1942062859</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD00155D4425C9</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Process '26728' failed to start. Port = 11904, Error Code = '-2147023436'.</Data>
        </EventData>
    </Event>
```

So it looks like maybe the ruby process fails to start?

**Comment by shibayan** [comment]
Thank you David.

Documentation and sample code in preparation, can be deployed quickly.

**Comment by shibayan** [comment]
I wrote how to deploy Ruby on Rails applications on Azure Web Sites.
https://github.com/shibayan/AzureRubyDeployment/blob/master/README.md

Try out more easily if you have provide a app repository sample/template from copying files to repository, and deployed.
https://github.com/shibayan/AzureRubyDeployment/tree/master/sample/template

I tried also deployed on Azure Web Sites samples.(Seems that might fail to deploy at Websites free tier)
http://rails-sample.azurewebsites.net/

**Comment by davidebbo** [comment]
@shibayan I put your sample in its own repo (https://github.com/davidebbo-test/RubyWebSite) to try it. It got pretty far in the install, but eventually failed with something related to building a native gem:

```
remote: Installing sass-rails 4.0.5
remote: Installing sdoc 0.4.1
remote: Installing sqlite3 1.3.10
remote:
remote: Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
remote:
remote:         d:/home/site/wwwroot/bin/ruby/1.9.3/bin/ruby.exe extconf.rb
remote:
remote: Gem files will remain installed in d:/home/site/wwwroot/bin/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/thin-1.6.3 for inspection.
remote: Results logged to d:/home/site/wwwroot/bin/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/thin-1.6.3/ext/thin_parser/gem_make.out
remote: An error occurred while installing thin (1.6.3), and Bundler cannot continue.
remote: Make sure that `gem install thin -v '1.6.3'` succeeds before bundling.
remote: An error has occurred during web site deployment.
remote: bundle install failed
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
```

Note that I didn't do any steps on the client, and maybe it was supposed to do some of those steps there and add them to the repo before pushing. Any chance that you can share a test repo that's exactly in the right state so it can be pushed?

As you can see, I'm pretty ignorant about Ruby, but I'm excited to see it work! :)

**Comment by takekazuomi** [comment]
I was also the same result
In my case, I was successful in re-deployed from portal
It is really strange

**Comment by shibayan** [comment]
@davidebbo This problem is currently under investigation, failed to create the process.
As @takekazuomi wrote, it successful in re-deployed from portal.

By the way, Is the limit on the number of processes in Azure Web Sites?
The following error occurred in Debug Console of the Kudu during the installation of gem.

```
[Win32Exception (0x80004005): Insufficient system resources exist to complete the requested service]
   System.Diagnostics.Process.CreatePipeWithSecurityAttributes(SafeFileHandle&amp; hReadPipe, SafeFileHandle&amp; hWritePipe, SECURITY_ATTRIBUTES lpPipeAttributes, Int32 nSize) +1815196
   System.Diagnostics.Process.CreatePipe(SafeFileHandle&amp; parentHandle, SafeFileHandle&amp; childHandle, Boolean parentInputs) +78
   System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) +444
   System.Diagnostics.Process.Start() +6813874
   Kudu.Services.PersistentCommandController.CreateProcess(String connectionId, String shell) +608
```

**Comment by davidebbo** [comment]
@takekazuomi indeed, after redeploying, it worked and the size runs. Puzzling! We should look deeper at what's happening.

@shibayan In Free and Shared modes, site resources are sandbox limited. But in Basic and Standard mode, sites are allowed to use any memory/CPU available on the machine. What mode was your site in? Also, can you tell me what I need to run in Kudu Console to repro this?

**Comment by shibayan** [comment]
@davidebbo It was confirmed that it is the same error in the Free and Basic.
Errors in the Debug Console of Kudu, I will reproduce open the Debug Console in bundle installing.
(To perform a bundle install again be necessary to remove the bin folder...)

@takekazuomi Deploying from the git, maybe affected that sh.exe is present in the parent process?

**Comment by shibayan** [comment]
It was resolved that the change in JRuby. I think it's Ruby problems.
https://github.com/shibayan/azure-jruby-sample
